### ISSUE TITLE
UnicodeDecodeError if unicode characters are entered into the title field

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#373]
## Steps to reproduce

Add e.g. a SamplePoint to a Client folder and enter a unicode character in the title.

## Current behavior

UnicodeDecodeError occurs

## Expected behavior

Title is correctly validated

## Screenshot (optional)

**Comment by ramonski** [comment]
Should be fixed with that PR: https://github.com/bikalims/bika.lims/issues/2302

**Comment by grulisco** [comment]
still a problem with senaite 1.1.6 - my cases e.g. calculation, analysis service
sample point as mentioned is OK
